In [3]:
#-*-author Yangami-*-
import numpy as np
import pandas as pd

# shape

In [4]:
#创建数组
a=np.array([1,2,3])
b=np.arange(9)
a,b,type(a)

(array([1, 2, 3]), array([0, 1, 2, 3, 4, 5, 6, 7, 8]), numpy.ndarray)

In [5]:
c=np.array([[[1,2,3],[2,4,6]],[[1,2,3],[2,4,6]]])
c

array([[[1, 2, 3],
        [2, 4, 6]],

       [[1, 2, 3],
        [2, 4, 6]]])

In [6]:
np.shape(c)

(2, 2, 3)

In [7]:
np.shape(a)

(3,)

In [8]:
np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [11]:
#数组转列表
c.tolist()

[[[1, 2, 3], [2, 4, 6]], [[1, 2, 3], [2, 4, 6]]]

# reshape

In [16]:
a=np.array([[1,2,3,4,5,6]])
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [31]:
a.reshape(2,3) 

np.array([60, 31, 54, 78,89,34,65,78,56,77,88,44 ]).reshape(3,4)

array([[60, 31, 54, 78],
       [89, 34, 65, 78],
       [56, 77, 88, 44]])

In [25]:
a.reshape(1,-1)


array([[1, 2, 3, 4, 5, 6]])

# 基本运算

In [32]:
a

array([[1, 2, 3, 4, 5, 6]])

In [33]:
a+1

array([[2, 3, 4, 5, 6, 7]])

In [35]:
a*2

array([[ 2,  4,  6,  8, 10, 12]])

In [36]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947]])

In [37]:
a

array([[1, 2, 3, 4, 5, 6]])

In [39]:
#条件选择返回bool值
a>2

array([[False, False,  True,  True,  True,  True]])

In [43]:
#bool值做索引
a[a>2]

array([3, 4, 5, 6])

# 拆分合并

In [44]:
a=a.reshape(2,3)

In [45]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
#取某行
a[1]

array([4, 5, 6])

In [50]:
#取某列
a[1,1:]

array([5, 6])

In [54]:
a[1][2]

6

In [51]:
#取元素
a[1,2],a[1][2]

(6, 6)

In [59]:
#拆分数组
a1=a[:,:1]
a2=a[:,1:]

print(a1,'\n',a2)


[[1]
 [4]] 
 [[2 3]
 [5 6]]


In [60]:
#合并数组
a1+a2

array([[ 3,  4],
       [ 9, 10]])

In [76]:
#hstack()\vstack()
hstack((a1,a2))

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
vstack((a[0],a[1]))

array([[1, 2, 3],
       [4, 5, 6]])

# 矩阵运算

In [64]:
a=np.arange(4).reshape(2,2)

In [65]:
a

array([[0, 1],
       [2, 3]])

In [66]:
#对应元素乘
a*a

array([[0, 1],
       [4, 9]])

In [67]:
#矩阵乘法
a.dot(a)

array([[ 2,  3],
       [ 6, 11]])

In [72]:
#转化为矩阵
a=np.matrix(a)
print(type(a))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [73]:
a+1

matrix([[1, 2],
        [3, 4]])

In [75]:
a

matrix([[0, 1],
        [2, 3]])

In [74]:
#矩阵乘法
b=a*a
b

matrix([[ 2,  3],
        [ 6, 11]])

In [197]:
#转置
b.T

matrix([[ 2,  6],
        [ 3, 11]])

In [198]:
#求逆
b.I

matrix([[ 2.75, -0.75],
        [-1.5 ,  0.5 ]])

# 广播机制

考虑维度不相等情况下数组的运算

In [212]:
arr1 = np.array([[0, 0, 0],[1, 1, 1],[2, 2, 2], [3, 3, 3]])  #arr1.shape = (4,3)
arr2 = np.array([1, 2, 3]).reshape(1,-1)    #arr2.shape = (1,3)
arr1,arr2

(array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]), array([[1, 2, 3]]))

In [213]:
arr_sum = arr1 + arr2
print(arr_sum)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


广播的原则：如果两个数组的后缘维度（trailing dimension，即从末尾开始算起的维度）的轴长度相符，或其中的一方的长度为1，则认为它们是广播兼容的。广播会在缺失和（或）长度为1的维度上进行。

![brodcast1](brodcast1.png)

In [77]:
arr1 = np.array([[0, 0, 0],[1, 1, 1],[2, 2, 2], [3, 3, 3]])  #arr1.shape = (4,3)
arr2 = np.array([[1],[2],[3],[4]])    #arr2.shape = (4, 1)
print(arr1,arr2)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]] [[1]
 [2]
 [3]
 [4]]


In [78]:
arr_sum = arr1 + arr2
print(arr_sum)

[[1 1 1]
 [3 3 3]
 [5 5 5]
 [7 7 7]]


![bd](brodcast2.png)

# 统计

In [82]:
#按行按列计算
a=np.arange(9).reshape(3,3)
a,np.shape(a)

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), (3, 3))

In [84]:
#直接求平均
np.mean(a)

4.0

In [246]:
#求每行平均值
np.mean(a,axis=1)

array([1., 4., 7.])

In [247]:
#求每列平均值
np.mean(a,axis=0)

array([3., 4., 5.])

##### 样本回归模型

$$ y_i = \hat{\beta_1} + \hat{\beta_2}x $$

In [266]:
'112,11'.split(',')

['112', '11']

In [88]:
txt=open('./  olsfit_data.txt').readlines()
data=[list(map(float,i)) for i in  list(map(lambda x:x[:-2].split('\t'),txt))]
data

[[1.0, 5.8398497],
 [2.0, 7.1220077],
 [3.0, 8.44177089],
 [4.0, 9.99793798],
 [5.0, 11.4928578],
 [6.0, 12.9253316],
 [7.0, 13.954791],
 [8.0, 14.827949],
 [9.0, 16.9480025],
 [10.0, 17.7126283],
 [11.0, 19.4835607],
 [12.0, 20.0063949],
 [13.0, 21.757987],
 [14.0, 22.5121804],
 [15.0, 24.3897803],
 [16.0, 25.749725],
 [17.0, 26.9591461],
 [18.0, 28.1525576],
 [19.0, 29.3286588],
 [20.0, 31.0870064],
 [21.0, 31.9189839],
 [22.0, 33.338666],
 [23.0, 35.0384887],
 [24.0, 36.0505391],
 [25.0, 37.1041033],
 [26.0, 38.1204212],
 [27.0, 39.9357521],
 [28.0, 40.8551978],
 [29.0, 42.7651319],
 [30.0, 43.9714338]]

In [89]:
data

[[1.0, 5.8398497],
 [2.0, 7.1220077],
 [3.0, 8.44177089],
 [4.0, 9.99793798],
 [5.0, 11.4928578],
 [6.0, 12.9253316],
 [7.0, 13.954791],
 [8.0, 14.827949],
 [9.0, 16.9480025],
 [10.0, 17.7126283],
 [11.0, 19.4835607],
 [12.0, 20.0063949],
 [13.0, 21.757987],
 [14.0, 22.5121804],
 [15.0, 24.3897803],
 [16.0, 25.749725],
 [17.0, 26.9591461],
 [18.0, 28.1525576],
 [19.0, 29.3286588],
 [20.0, 31.0870064],
 [21.0, 31.9189839],
 [22.0, 33.338666],
 [23.0, 35.0384887],
 [24.0, 36.0505391],
 [25.0, 37.1041033],
 [26.0, 38.1204212],
 [27.0, 39.9357521],
 [28.0, 40.8551978],
 [29.0, 42.7651319],
 [30.0, 43.9714338]]

In [91]:
X=np.array(data)[:,0]
Y=np.array(data)[:,1]

In [92]:
X,Y

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29., 30.]),
 array([ 5.8398497 ,  7.1220077 ,  8.44177089,  9.99793798, 11.4928578 ,
        12.9253316 , 13.954791  , 14.827949  , 16.9480025 , 17.7126283 ,
        19.4835607 , 20.0063949 , 21.757987  , 22.5121804 , 24.3897803 ,
        25.749725  , 26.9591461 , 28.1525576 , 29.3286588 , 31.0870064 ,
        31.9189839 , 33.338666  , 35.0384887 , 36.0505391 , 37.1041033 ,
        38.1204212 , 39.9357521 , 40.8551978 , 42.7651319 , 43.9714338 ]))

In [94]:
#线性回归
np.polyfit(X,Y,1)

array([1.30148078, 4.75334269])

##### 矩阵形式

$$ Y=X\hat{\beta}$$

#### 求解回归系数

$$\beta=(X'X)^{-1}X'Y$$

### 练习：用OLS的矩阵定义式计算回归系数$$\hat{\beta_1} 、 \hat{\beta_2}$$

#### 已知样本的自变量因变量x、y及矩阵公式简介
![ols](回归矩阵式1.png)
![ols2](回归矩阵式2.png)

###### answer
X=X.reshape(-1,1)
X=hstack((np.array(([1]*len(X))).reshape(-1,1),X))
np.mat(X.T.dot(X)).I.dot(X.T).dot(Y)

In [ ]:
X=X.reshape(-1,1)
X=hstack((np.array(([1]*len(X))).reshape(-1,1),X))
np.mat(X.T.dot(X)).I.dot(X.T).dot(Y)