In [257]:
#Pandas官方文档:http://pandas.pydata.org/pandas-docs/stable/
#-*-author Yangami-*-
import pandas as pd
import numpy as np

# 一、基本类型

pandas包含两种数据类型：series和dataframe。
series是一种一维数据结构，每一个元素都带有一个索引，与一维数组的含义相似，其中索引可以为数字或字符串。series结构名称：

![](pandas1.png)

#### 用列表、数组和字典构建series

In [261]:
lst = list('abcedfg')   # 列表
arr = np.arange(7)                      # 数组
# 构建方法
ser1 = pd.Series(lst)
ser2 = pd.Series(arr)
#一维序列series会自动添加索引
print(ser1)
print(ser2)

0    a
1    b
2    c
3    e
4    d
5    f
6    g
dtype: object
0    0
1    1
2    2
3    3
4    4
5    5
6    6
dtype: int32


In [262]:
#构建字典转series
dic = {'及时雨':'宋江','豹子头':'林冲','花和尚':'鲁智深','浪子':'燕青'}
ser3 = pd.Series(dic)
ser3

及时雨     宋江
豹子头     林冲
花和尚    鲁智深
浪子      燕青
dtype: object

In [269]:
dict(zip(lst, arr))

{'a': 0, 'b': 1, 'c': 2, 'e': 3, 'd': 4, 'f': 5, 'g': 6}

In [270]:
dict(zip(lst, arr))
#用两序列构建字典转series
mydict = dict(zip(lst, arr))             # 字典
ser3 = pd.Series(mydict)
ser3

a    0
b    1
c    2
e    3
d    4
f    5
g    6
dtype: int64

In [271]:
#series拥有许多np.array的性质
ser1_=ser2+1
print(ser1_)
ser3.shape

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32


(7,)

In [277]:
np.array([[1,2,3],[2,5,1]]).tolist()

[[1, 2, 3], [2, 5, 1]]

In [272]:
#将series变序列索引信息会消失
ser3.tolist()

[0, 1, 2, 3, 4, 5, 6]

dataframe是一种二维数据结构，数据以表格形式（与excel类似）存储，有对应的行和列。dataframe结构名称：

![](pandas2.png)

#### 字典构建dataframe

In [278]:
#键为df的列名值为该列元素
df=pd.DataFrame({'a':[1,2,3],'b':['1','2','3']})
df

a  b
0  1  1
1  2  2
2  3  3

In [281]:
#bug辨析（If using all scalar values, you must pass an index）
df=pd.DataFrame({'a':1,'b':2})
df

ValueError: If using all scalar values, you must pass an index

In [282]:
pd.DataFrame(dic,[0])

及时雨 豹子头  花和尚  浪子
0  宋江  林冲  鲁智深  燕青

In [286]:
#事实上自定义index更方便操作且少出bug
airqlt=pd.DataFrame({'weather':['sunny','cloudy','cloudy'],
                     'temp':[13,17,12]},index=['2019-01-01','2019-01-02','2019-01-03'])
airqlt

weather  temp
2019-01-01   sunny    13
2019-01-02  cloudy    17
2019-01-03  cloudy    12

dataframe取值

In [287]:
#取列
airqlt['weather']

2019-01-01     sunny
2019-01-02    cloudy
2019-01-03    cloudy
Name: weather, dtype: object

In [288]:
#取行
airqlt.loc['2019-01-01']

'sunny'

# 二、pandas读文件（IO工具）

打开csv文件

In [303]:
csvfile=pd.read_csv(open('hotel_data.csv'),index_col=0)

In [304]:
csvfile

价格（元/晚）  \
名称                                             
西安金莎国际酒店                                 420   
西安君乐城堡酒店                                 533   
美豪丽致酒店(西安未央路店)                           328   
维慕智能酒店(西安高铁北客站旗舰店)                       266   
西安悦豪酒店                                   442   
秦唐一号酒店(西安钟楼店)                            348   
如家精选酒店(西安钟楼店)                            256   
甲字精品酒店(西安钟楼回民街店)                         184   
陕西世纪金源大饭店                                378   
西安钟楼回民街亚朵酒店                              487   
美丽豪酒店(西安曲江大雁塔小寨会展中心店)                    449   
璞隐酒店(西安大雁塔店)                             289   
美豪酒店(西安龙首店)                              300   
喜客五间唐中式酒店(西安大雁塔博物馆小寨会展中心店)(原小寨大雁塔店)      278   
西安皇城豪门酒店                                 439   
西安荣民国际饭店                                 308   
丽途精选酒店(西安大雁塔曲江店)                         288   
华辰酒店(西安钟楼东大街明城墙店)                        152   
西安阳光国际大酒店                                346   
西安阳光国际大酒店                                346   
柠檬酒店(西安金花店)                              272   
斯维登精品公寓(西安钟楼火车站)                         240   
西安紫金山大酒店                                 174   
西安美道酒店                                   269   
美豪酒店(西安市政府机场高铁北客站店)                      294   
左右客设计师精品酒店(西安钟鼓楼回民街店)(原古都店)              408   
兴阳精选酒店(西安钟鼓楼回民街店)                        136   
左洛精品酒店(西安明城墙永兴坊店)(原钟鼓楼东门店)               109   
西安古都文化大酒店(原古都新世界大酒店)                     329   
美豪丽致酒店(西安长乐公园店)                          359   
...                                      ...   
西安目心者青年旅舍                                 44   
西安目心者青年旅舍                                 44   
西安永兴宾馆                                    57   
西安馨凯商务宾馆                                  67   
周至皇朝商务宾馆                                  87   
周至优莱客酒店                                   87   
周至优莱客酒店                                   87   
西安沐冉之家酒店(原钟鼓楼紫默公寓酒店)                     107   
西安瑞豪宾馆                                    74   
西安大象民宿雁塔店                                517   
西安会朋快捷酒店                                  89   
西安飞天商务酒店                                 136   
西安毛小九的家普通公寓(龙首北路-未央路口店)                  197   
咸阳舒然快捷酒店                                  97   
西安旭日宾馆苏席村店                                57   
西安天乙宾馆                                    39   
宜心高档酒店式公寓(西安西工大店)                         48   
芙蓉酒店公寓(西安唐都医院店)                           65   
中玺国际酒店公寓(西安华夏世纪城店)                       295   
兴华宾馆(西安北池头店)                             127   
芙蓉宾馆(西安凤城三路店)                             88   
西安小满贰拾肆公寓酒店                              240   
西安麦思尔德公寓(北大街分店)                          394   
西安咸阳国际机场久佳意宾馆                             94   
西安米朵时尚精品公寓                               207   
西安福茂宾馆                                   113   
白蜗牛宾馆(西安草滩医学院店)                           49   
非繁·鑫乐天酒店(西安大学城长安广场店)                     159   
西安金莱主题酒店韦曲汽车南站店                          127   
西安将军山三笙舍度假酒店                             285   

                                                                                    地址  \
名称                                                                                       
西安金莎国际酒店                                                   [小寨/历史博物馆]\n长安中路65号\n\n\n地图   
西安君乐城堡酒店                                              [钟鼓楼/回民街/市中心]\n环城南路西段12号\n\n\n地图   
美豪丽致酒店(西安未央路店)                       [大明宫万达/大明宫遗址公园]\n未央路149号(凤城三路与未央路十字东北角)地铁2号线图书...   
维慕智能酒店(西安高铁北客站旗舰店)                        [西安高铁站火车北站/西安市政中心]\n凤城十一路与文景路十字向西50米\n\n\n地图   
西安悦豪酒店                                        [西安市高新技术开发区]\n二环南路西段180号\n\n\n地图\n\n\n街景   
秦唐一号酒店(西安钟楼店)                                       [钟鼓楼/回民街/市中心]\n南大街东木头市176号\n\n\n地图   
如家精选酒店(西安钟楼店)                         [钟鼓楼/回民街/市中心]\n南大街8号(和西贝莜面村同一栋楼)\n\n\n地图\n\n\n街景   
甲字精品酒店(西安钟楼回民街店)                                  [钟鼓楼/回民街/市中心]\n案板街3号\n\n\n地图\n\n\n街景   
陕西世纪金源大饭店                                                [新城区]\n建工路19号\n\n\n地图\n\n\n街景   
西安钟楼回民街亚朵酒店           

打开文本文件（.txt）

In [15]:
pd.read_csv('stockfile.txt',sep='\t')

date   open  close   high    low      volume         money
0     2005-01-04    NaN    NaN    NaN    NaN         NaN           NaN
1     2005-01-05    NaN    NaN    NaN    NaN         NaN           NaN
2     2005-01-06    NaN    NaN    NaN    NaN         NaN           NaN
3     2005-01-07    NaN    NaN    NaN    NaN         NaN           NaN
4     2005-01-10    NaN    NaN    NaN    NaN         NaN           NaN
5     2005-01-11    NaN    NaN    NaN    NaN         NaN           NaN
6     2005-01-12    NaN    NaN    NaN    NaN         NaN           NaN
7     2005-01-13    NaN    NaN    NaN    NaN         NaN           NaN
8     2005-01-14    NaN    NaN    NaN    NaN         NaN           NaN
9     2005-01-17    NaN    NaN    NaN    NaN         NaN           NaN
10    2005-01-18    NaN    NaN    NaN    NaN         NaN           NaN
11    2005-01-19    NaN    NaN    NaN    NaN         NaN           NaN
12    2005-01-20    NaN    NaN    NaN    NaN         NaN           NaN
13    2005-01-21    NaN    NaN    NaN    NaN         NaN           NaN
14    2005-01-24    NaN    NaN    NaN    NaN         NaN           NaN
15    2005-01-25    NaN    NaN    NaN    NaN         NaN           NaN
16    2005-01-26    NaN    NaN    NaN    NaN         NaN           NaN
17    2005-01-27    NaN    NaN    NaN    NaN         NaN           NaN
18    2005-01-28    NaN    NaN    NaN    NaN         NaN           NaN
19    2005-01-31    NaN    NaN    NaN    NaN         NaN           NaN
20    2005-02-01    NaN    NaN    NaN    NaN         NaN           NaN
21    2005-02-02    NaN    NaN    NaN    NaN         NaN           NaN
22    2005-02-03    NaN    NaN    NaN    NaN         NaN           NaN
23    2005-02-04    NaN    NaN    NaN    NaN         NaN           NaN
24    2005-02-16    NaN    NaN    NaN    NaN         NaN           NaN
25    2005-02-17    NaN    NaN    NaN    NaN         NaN           NaN
26    2005-02-18    NaN    NaN    NaN    NaN         NaN           NaN
27    2005-02-21    NaN    NaN    NaN    NaN         NaN           NaN
28    2005-02-22    NaN    NaN    NaN    NaN         NaN           NaN
29    2005-02-23    NaN    NaN    NaN    NaN         NaN           NaN
...          ...    ...    ...    ...    ...         ...           ...
3372  2018-11-19  14.69  14.87  14.88  14.55   4683967.0  6.912939e+07
3373  2018-11-20  14.71  14.80  14.95  14.71   4699213.0  6.963872e+07
3374  2018-11-21  14.69  14.75  14.80  14.52   2533450.0  3.711472e+07
3375  2018-11-22  14.76  14.67  14.77  14.61   1712906.0  2.511171e+07
3376  2018-11-23  14.68  14.39  14.72  14.18   2181717.0  3.146170e+07
3377  2018-11-26  14.39  14.20  14.49  14.16   1516159.0  2.170950e+07
3378  2018-11-27  14.26  14.25  14.44  14.19   1442989.0  2.062111e+07
3379  2018-11-28  14.28  14.30  14.34  14.14   2014963.0  2.869692e+07
3380  2018-11-29  14.33  14.02  14.39  14.01   3228414.0  4.580551e+07
3381  2018-11-30  14.03  14.14  14.16  13.98   2219750.0  3.123554e+07
3382  2018-12-03  14.46  14.58  14.67  14.36   4275620.0  6.218882e+07
3383  2018-12-04  14.46  14.82  14.89  14.46   2825753.0  4.163700e+07
3384  2018-12-05  14.82  14.84  14.92  14.61   3437611.0  5.095317e+07
3385  2018-12-06  14.75  14.68  14.92  14.60   2166222.0  3.200764e+07
3386  2018-12-07  14.71  14.66  14.84  14.65   1681473.0  2.477677e+07
3387  2018-12-10  14.76  14.60  14.99  14.56   3255743.0  4.807132e+07
3388  2018-12-11  14.62  15.04  15.08  14.62   3698661.0  5.510945e+07
3389  2018-12-12  15.04  15.24  15.42  15.00   4846495.0  7.399672e+07
3390  2018-12-13  15.20  15.77  15.85  15.20   5183881.0  8.120530e+07
3391  2018-12-14  15.62  15.65  15.98  15.62   5556082.0  8.778051e+07
3392  2018-12-17  15.76  16.23  16.36  15.70   6589871.0  1.059621e+08
3393  2018-12-18  16.07  16.13  16.30  15.57   4751914.0  7.572821e+07
3394  2018-12-19  15.88  15.90  16.18  15.80   3298171.0  5.283019e+07
3395  2018-12-20  15.90  15.99  16.24  15.76   2768679.0  4.429820e+07
3396  2018-12-21  15.81  15.97  16.2

打开excel

In [16]:
#excel格式并不整齐，修改header为列名的索引，修改index_col为行名的索引

In [298]:
pd.read_excel('excel_data.xls',header=2,index_col=0)#, sheet_name='Sheet1',,)

农、林、牧、渔业       采矿业  \
                            产  出\n\n        投  入                       
NaN                                                    NaN       NaN   
NaN                                                    NaN       NaN   
NaN                                                    NaN       NaN   
 总投入                                              1.000000  1.000000   
 中间投入合计                                           0.413839  0.527095   
   农、林、牧、渔业                                       0.140657  0.002677   
   采矿业                                            0.000677  0.074990   
   食品、饮料制造及烟草制品业                                  0.096175  0.002212   
   纺织、服装及皮革产品制造业                                  0.000555  0.004678   
   其他制造业                                          0.003005  0.011895   
   电力、热力及水的生产和供应业                                 0.009559  0.081900   
   炼焦、燃气及石油加工业                                    0.008102  0.037564   
   化学工业                                           0.076272  0.038296   
   非金属矿物制品业                                       0.001417  0.013054   
   金属产品制造业                                        0.002984  0.053439   
   机械设备制造业                                        0.010861  0.096306   
   建筑业                                            0.000232  0.000926   
   运输仓储邮政、信息传输、计算机服务和软件业                          0.019855  0.043897   
   批发零售贸易、住宿和餐饮业                                  0.017420  0.022345   
   房地产业、租赁和商务服务业                                  0.001674  0.003821   
   金融业                                            0.008311  0.014923   
   其他服务业                                          0.016082  0.024172   
 增加值合计                                            0.586161  0.472905   
   劳动者报酬                                          0.555941  0.166655   
   生产税净额                                          0.000978  0.086233   
   固定资产折旧                                         0.029242  0.051380   
   营业盈余                                                NaN  0.168638   
NaN                                                    NaN       NaN   

                                                      食品、饮料制造       纺织、服装及  \
                            产  出\n\n        投  入                             
NaN                                                    及烟草制品业      皮革产品制造业   
NaN                                                       NaN          NaN   
NaN                                                       NaN          NaN   
 总投入                                                        1            1   
 中间投入合计                                               0.75644     0.793246   
   农、林、牧、渔业                                          0.381574       0.1019   
   采矿业                                             0.00358726   0.00430569   
   食品、饮料制造及烟草制品业                                     0.190394    0.0249679   
   纺织、服装及皮革产品制造业                                   0.00179312     0.434754   
   其他制造业                                            0.0244171    0.0164334   
   电力、热力及水的生产和供应业                                    0.011486    0.0165314   
   炼焦、燃气及石油加工业                                     0.00365267   0.00493321   
   化学工业                                             0.0294399    0.0941772   
   非金属矿物制品业                                        0.00676645   0.00187685   
   金属产品制造业                                         0.00579323   0.00382594   
   机械设备制造业                                         0.00753951    0.0159058   
   建筑业                                            0.000257389  0.000227516   
   运输仓储邮政、信息传输、计算机服务和软件业                             0.028445    0.0216404   
   批发零售贸易、住宿和餐饮业                                    0.0293204    0.0190389   
   房地产业、租赁和商务服务业                                    0.0152138    0.0137026   
   金融业                                             0.00938282     0.012055   
   其他服务业                                           0.00737769   0.00696951   
 增加值合计           

# 三、dataframe使用

In [305]:
#以csv文件的hotel数据为例学习df方法
hotel=csvfile

#### DF基本方法

In [306]:
#行列索引
print(hotel.columns)
hotel.index

Index(['价格（元/晚）', '地址', '特点', '已购人数', '评分', '收藏', '简评', '评价'], dtype='object')


Index(['西安金莎国际酒店', '西安君乐城堡酒店', '美豪丽致酒店(西安未央路店)', '维慕智能酒店(西安高铁北客站旗舰店)',
       '西安悦豪酒店', '秦唐一号酒店(西安钟楼店)', '如家精选酒店(西安钟楼店)', '甲字精品酒店(西安钟楼回民街店)',
       '陕西世纪金源大饭店', '西安钟楼回民街亚朵酒店',
       ...
       '芙蓉宾馆(西安凤城三路店)', '西安小满贰拾肆公寓酒店', '西安麦思尔德公寓(北大街分店)', '西安咸阳国际机场久佳意宾馆',
       '西安米朵时尚精品公寓', '西安福茂宾馆', '白蜗牛宾馆(西安草滩医学院店)', '非繁·鑫乐天酒店(西安大学城长安广场店)',
       '西安金莱主题酒店韦曲汽车南站店', '西安将军山三笙舍度假酒店'],
      dtype='object', name='名称', length=2097)

In [307]:
#取某列
hotel['已购人数'],type(hotel['已购人数'])

(名称
 西安金莎国际酒店                               14536
 西安君乐城堡酒店                                5164
 美豪丽致酒店(西安未央路店)                          1568
 维慕智能酒店(西安高铁北客站旗舰店)                      1711
 西安悦豪酒店                                  2396
 秦唐一号酒店(西安钟楼店)                          10342
 如家精选酒店(西安钟楼店)                            426
 甲字精品酒店(西安钟楼回民街店)                        3263
 陕西世纪金源大饭店                              14579
 西安钟楼回民街亚朵酒店                             2485
 美丽豪酒店(西安曲江大雁塔小寨会展中心店)                   5960
 璞隐酒店(西安大雁塔店)                            4629
 美豪酒店(西安龙首店)                             4398
 喜客五间唐中式酒店(西安大雁塔博物馆小寨会展中心店)(原小寨大雁塔店)     4501
 西安皇城豪门酒店                                9030
 西安荣民国际饭店                                7615
 丽途精选酒店(西安大雁塔曲江店)                        4836
 华辰酒店(西安钟楼东大街明城墙店)                       5502
 西安阳光国际大酒店                               4074
 西安阳光国际大酒店                               4074
 柠檬酒店(西安金花店)                             4727
 斯维登精品公寓(西安钟楼火车站)             

In [21]:
#取某行 iloc&loc
#取索引为西安永兴宾馆的行
hotel.loc['西安永兴宾馆'],type(hotel['评分'])

(价格（元/晚）                                     57
 地址         [胡家庙/长缨东路]\n长缨东路41号\n\n\n地图\n\n\n街景
 特点                                        地铁周边
 已购人数                                         9
 评分                                        3.0?
 收藏                                           3
 简评                                         一般般
 评价                                        床品舒适
 Name: 西安永兴宾馆, dtype: object, pandas.core.series.Series)

In [313]:
#取第一行
hotel.iloc[0,]

价格（元/晚）                            420
地址         [小寨/历史博物馆]\n长安中路65号\n\n\n地图
特点                                休闲度假
已购人数                             14536
评分                                 4.6
收藏                                   1
简评                                 棒极了
评价                                交通便利
Name: 西安金莎国际酒店, dtype: object

In [314]:
#更改列索引名,不改变表格内容
hotel.columns=['价格']+list(hotel.columns)[1:]

In [316]:
hotel['价格']

名称
西安金莎国际酒店                               420
西安君乐城堡酒店                               533
美豪丽致酒店(西安未央路店)                         328
维慕智能酒店(西安高铁北客站旗舰店)                     266
西安悦豪酒店                                 442
秦唐一号酒店(西安钟楼店)                          348
如家精选酒店(西安钟楼店)                          256
甲字精品酒店(西安钟楼回民街店)                       184
陕西世纪金源大饭店                              378
西安钟楼回民街亚朵酒店                            487
美丽豪酒店(西安曲江大雁塔小寨会展中心店)                  449
璞隐酒店(西安大雁塔店)                           289
美豪酒店(西安龙首店)                            300
喜客五间唐中式酒店(西安大雁塔博物馆小寨会展中心店)(原小寨大雁塔店)    278
西安皇城豪门酒店                               439
西安荣民国际饭店                               308
丽途精选酒店(西安大雁塔曲江店)                       288
华辰酒店(西安钟楼东大街明城墙店)                      152
西安阳光国际大酒店                              346
西安阳光国际大酒店                              346
柠檬酒店(西安金花店)                            272
斯维登精品公寓(西安钟楼火车站)                       240
西安紫金山大酒店                               174
西安美道酒店  

In [25]:
price=hotel['价格']
locat=hotel['地址']
score=hotel['评分']
feature=hotel['特点']

In [26]:
#异常数据处理
score[0]

'4.6?'

In [27]:
newlst=[]
for i in score:
    newlst.append(float(i[:-1]))
newlst

[4.6,
 4.4,
 5.0,
 4.7,
 4.6,
 4.7,
 4.7,
 4.5,
 4.9,
 4.8,
 4.9,
 4.9,
 4.6,
 4.8,
 4.5,
 4.6,
 4.6,
 4.5,
 4.6,
 4.6,
 4.7,
 4.7,
 4.3,
 4.7,
 4.9,
 4.7,
 4.7,
 4.9,
 4.5,
 4.9,
 4.7,
 4.7,
 5.0,
 4.7,
 4.4,
 4.2,
 4.9,
 4.9,
 4.6,
 4.5,
 4.6,
 4.8,
 4.6,
 4.9,
 4.6,
 4.7,
 4.8,
 4.7,
 4.6,
 4.6,
 5.0,
 4.6,
 4.7,
 4.8,
 4.9,
 4.5,
 4.7,
 4.8,
 4.9,
 4.9,
 4.7,
 4.7,
 4.9,
 4.9,
 4.6,
 4.6,
 4.5,
 4.4,
 4.6,
 4.9,
 4.1,
 4.2,
 4.7,
 4.5,
 4.6,
 4.5,
 4.6,
 4.6,
 4.7,
 4.6,
 4.8,
 4.3,
 4.7,
 4.5,
 4.8,
 4.5,
 4.9,
 4.5,
 4.7,
 4.4,
 4.3,
 4.8,
 4.6,
 4.7,
 4.4,
 4.6,
 5.0,
 4.8,
 4.2,
 4.9,
 4.4,
 4.9,
 4.9,
 4.7,
 4.8,
 4.6,
 4.6,
 4.7,
 4.7,
 4.8,
 4.7,
 4.8,
 4.2,
 4.5,
 4.8,
 4.9,
 4.9,
 4.9,
 4.6,
 4.7,
 4.5,
 4.7,
 4.7,
 4.8,
 4.6,
 4.8,
 5.0,
 4.5,
 4.6,
 4.9,
 4.9,
 4.9,
 4.8,
 4.8,
 4.7,
 4.9,
 4.5,
 4.9,
 4.9,
 4.8,
 4.9,
 4.4,
 4.7,
 4.9,
 4.7,
 4.5,
 4.7,
 4.6,
 4.5,
 4.5,
 4.8,
 4.6,
 4.7,
 4.9,
 4.5,
 4.8,
 4.7,
 4.5,
 4.7,
 4.6,
 4.8,
 4.7,
 4.8,
 4.2,
 4.7,
 4.5,
 4.8

In [312]:
hotel['评分']=newlst

#### 价格数据简析

In [237]:
#简单描述性分析
mean(price),np.percentile(price, [25, 50, 75])

(194.8559847401049, array([ 96., 154., 237.]))

In [321]:
tdt_dic={
    "location": {
        "lon": "116.001688",
        "level": "地名地址",
        "lat": "40.453228"
    },
    "status": "0",
    "msg": "ok",
    "searchVersion": "4.8.0"
}
tdt_dic['location']['lon'],tdt_dic['location']['lat']

('116.001688', '40.453228')

In [30]:
#计算简单相关系数
hotel[['价格','收藏','评分','已购人数']].corr()

价格        收藏        评分      已购人数
价格    1.000000  0.019743  0.249379  0.383060
收藏    0.019743  1.000000  0.028583  0.015337
评分    0.249379  0.028583  1.000000  0.179716
已购人数  0.383060  0.015337  0.179716  1.000000

#### 位置信息计算距离指标

In [31]:
#分析位置数据（[]内为附近地标[]后为具体位置）ps:
locat[0]

'[小寨/历史博物馆]\n长安中路65号\n\n\n地图'

![,](携程网站.png)

In [32]:
locat[0][1:locat[0].find(']')]

'小寨/历史博物馆'

In [33]:
locat[0][1:locat[0].find(']')].split('/')

['小寨', '历史博物馆']

In [34]:
#具体位置
locat[0].split('\n'),locat[0].split('\n')[1]

(['[小寨/历史博物馆]', '长安中路65号', '', '', '地图'], '长安中路65号')

In [35]:
#嵌入循环
centers=[]
htl_loc=[]
for i in range(len(locat)):
    centers.append(locat[i][1:locat[i].find(']')].split('/'))
    htl_loc.append(locat[i].split('\n')[1])

In [36]:
centers,htl_loc

([['小寨', '历史博物馆'],
  ['钟鼓楼', '回民街', '市中心'],
  ['大明宫万达', '大明宫遗址公园'],
  ['西安高铁站火车北站', '西安市政中心'],
  ['西安市高新技术开发区'],
  ['钟鼓楼', '回民街', '市中心'],
  ['钟鼓楼', '回民街', '市中心'],
  ['钟鼓楼', '回民街', '市中心'],
  ['新城区'],
  ['钟鼓楼', '回民街', '市中心'],
  ['电视塔', '国展中心'],
  ['大雁塔', '曲江旅游区'],
  ['北关', '龙首村'],
  ['大雁塔', '曲江旅游区'],
  ['钟鼓楼', '回民街', '市中心'],
  ['钟鼓楼', '回民街', '市中心'],
  ['大雁塔', '曲江旅游区'],
  ['钟鼓楼', '回民街', '市中心'],
  ['钟鼓楼', '回民街', '市中心'],
  ['钟鼓楼', '回民街', '市中心'],
  ['城东', '西京医院', '小商品批发市场'],
  ['钟鼓楼', '回民街', '市中心'],
  ['钟鼓楼', '回民街', '市中心'],
  ['西安市高新技术开发区'],
  ['西安高铁站火车北站', '西安市政中心'],
  ['钟鼓楼', '回民街', '市中心'],
  ['钟鼓楼', '回民街', '市中心'],
  ['钟鼓楼', '回民街', '市中心'],
  ['钟鼓楼', '回民街', '市中心'],
  ['城东', '西京医院', '小商品批发市场'],
  ['小寨', '历史博物馆'],
  ['电视塔', '国展中心'],
  ['高新管委会', '绿地会展中心'],
  ['大雁塔', '曲江旅游区'],
  ['城东', '西京医院', '小商品批发市场'],
  ['西稍门', '机场大巴站'],
  ['市图书馆', '凤城二路'],
  ['大明宫万达', '大明宫遗址公园'],
  ['城南', '李家村万达广场'],
  ['钟鼓楼', '回民街', '市中心'],
  ['钟鼓楼', '回民街', '市中心'],
  ['西安高铁站火车北站', '西安市政中心'],
  ['小寨', '历史博物馆'],
  ['钟鼓楼', '

地标取平均经纬度，具体位置取经纬度

In [239]:
#高德/百度/天地图获取经纬度
import requests
def geocodeG(address):
    par = {'address': address, 'key': 'cb649a25c1f81c1451adbeca73623251'}
    base = 'http://restapi.amap.com/v3/geocode/geo'
    response = requests.get(base, par)
    answer = response.json()
    GPS=answer['geocodes'][0]['location'].split(",")
    return GPS[0],GPS[1]
def geocodeB(address):
    ak='nAhF2RDAVOYEp6prqiNg9HamkZ3zGiSr'#百度http://lbsyun.baidu.com/申请ak
    
    base = "http://api.map.baidu.com/geocoder/v2/?address=" + address + "&output=json&ak="
    response = requests.get(base+ak)
    answer = response.json()
    return answer['result']['location']['lng'],answer['result']['location']['lat']
def geocodeD(address):
    ak='09ddeac833d7ed2d43e1bfa978df2faf'#天地图http://lbs.tianditu.gov.cn/server/geocodinginterface.html
    base='http://api.tianditu.gov.cn/geocoder?ds={"keyWord":"'+address+'"}&tk='
    response = requests.get(base+ak)
    answer = response.json()
    return answer['location']['lon'],answer['location']['lat']


In [248]:
from math import radians, cos, sin, asin, sqrt

#计算两点间距离-km
def Distance(lng1,lat1,lng2,lat2):
    lng1, lat1, lng2, lat2 = map(radians, [lng1, lat1, lng2, lat2])
    dlon=lng2-lng1
    dlat=lat2-lat1
    a=sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2 
    dis=2*asin(sqrt(a))*6371
    return dis

In [249]:
#test
geocodeG('小寨'),geocodeG('历史博物馆'),geocodeG('小寨,历史博物馆')

(('109.023056', '34.275948'),
 ('118.405998', '37.057858'),
 ('114.898956', '36.848186'))

In [250]:
#test
geocodeG('钟鼓楼')

IndexError: list index out of range

In [251]:
#计算酒店与中心地距离 计算前五十个示例
dist=[]
for i in zip(centers[:50],htl_loc[:50]):
    l=[]
    for c in i[0]:
        try:
            l.append(geocodeG(c)) 
        except:
            pass
    if len(l)==0:
        continue
    #观察数组形式经纬度
    print(np.array([[float(j[0]),float(j[1])] for j in l]))
    center=np.mean(np.array([[float(j[0]),float(j[1])] for j in l]),axis=0)        
    try:
        loc=[float(_) for _ in geocodeG(i[1])]
    except:
        continue
    print(center[1],center[0],loc[1],loc[0])
    dist.append(Distance(center[1],center[0],loc[1],loc[0]))
    print(i)

[[109.023056  34.275948]
 [118.405998  37.057858]]
35.666903000000005 113.714527 34.226567 108.947716
(['小寨', '历史博物馆'], '长安中路65号')
[[111.726574  40.775756]
 [103.7481    29.559998]]
35.167877000000004 107.737337 34.24884 108.945099
(['钟鼓楼', '回民街', '市中心'], '环城南路西段12号')
[[108.972244  34.314186]
 [109.744057  34.385696]]
34.349941 109.3581505 40.454839 124.065612
(['大明宫万达', '大明宫遗址公园'], '未央路149号(凤城三路与未央路十字东北角)地铁2号线图书馆站A口')
[[108.947     34.292   ]
 [108.940174  34.341568]]
[[108.906382  34.233743]]
34.233743 108.906382 34.241371 108.902344
(['西安市高新技术开发区'], '二环南路西段180号')
[[111.726574  40.775756]
 [103.7481    29.559998]]
35.167877000000004 107.737337 28.241402 117.178024
(['钟鼓楼', '回民街', '市中心'], '南大街东木头市176号')
[[111.726574  40.775756]
 [103.7481    29.559998]]
35.167877000000004 107.737337 34.256149 108.947182
(['钟鼓楼', '回民街', '市中心'], '南大街8号(和西贝莜面村同一栋楼)')
[[111.726574  40.775756]
 [103.7481    29.559998]]
35.167877000000004 107.737337 34.260342 108.950821
(['钟鼓楼', '回民街', '市中心'], '案板街3号')
[[10

In [252]:
#将前50个样本提取出来作为新数据
newdata=pd.DataFrame(hotel.iloc[:len(dist),])

In [253]:
#为新数据增添距离属性（新增列）
newdata['dist']=dist

In [254]:
newdata

价格  \
名称                                         
西安金莎国际酒店                             420   
西安君乐城堡酒店                             533   
美豪丽致酒店(西安未央路店)                       328   
维慕智能酒店(西安高铁北客站旗舰店)                   266   
西安悦豪酒店                               442   
秦唐一号酒店(西安钟楼店)                        348   
如家精选酒店(西安钟楼店)                        256   
甲字精品酒店(西安钟楼回民街店)                     184   
陕西世纪金源大饭店                            378   
西安钟楼回民街亚朵酒店                          487   
美丽豪酒店(西安曲江大雁塔小寨会展中心店)                449   
璞隐酒店(西安大雁塔店)                         289   
美豪酒店(西安龙首店)                          300   
喜客五间唐中式酒店(西安大雁塔博物馆小寨会展中心店)(原小寨大雁塔店)  278   
西安皇城豪门酒店                             439   
西安荣民国际饭店                             308   
丽途精选酒店(西安大雁塔曲江店)                     288   
华辰酒店(西安钟楼东大街明城墙店)                    152   
西安阳光国际大酒店                            346   
西安阳光国际大酒店                            346   
柠檬酒店(西安金花店)                          272   
斯维登精品公寓(西安钟楼火车站)                     240   
西安紫金山大酒店                             174   
西安美道酒店                               269   
美豪酒店(西安市政府机场高铁北客站店)                  294   
左右客设计师精品酒店(西安钟鼓楼回民街店)(原古都店)          408   
兴阳精选酒店(西安钟鼓楼回民街店)                    136   
左洛精品酒店(西安明城墙永兴坊店)(原钟鼓楼东门店)           109   
西安古都文化大酒店(原古都新世界大酒店)                 329   
美豪丽致酒店(西安长乐公园店)                      359   
美豪酒店(西安朱雀店)                          379   
雅缦智选酒店(西安会展中心店)                      428   
西安高新锦业路亚朵酒店                          350   
和颐酒店(西安大雁塔地铁站店)                      288   
西安海景国际酒店                             276   
天朗草阳酒店(西安西稍门机场大巴店)                   169   
西安名都国际酒店                             374   
美豪丽致酒店(西安北二环店)(原华帝金座店)               328   
柠檬酒店(西安南门店)                          298   
美莎酒店(西安钟楼南门店)                        299   
华美达兆瑞酒店(西安钟楼店)                       538   

                                                                                    地址  \
名称                                                                                       
西安金莎国际酒店                                                   [小寨/历史博物馆]\n长安中路65号\n\n\n地图   
西安君乐城堡酒店                                              [钟鼓楼/回民街/市中心]\n环城南路西段12号\n\n\n地图   
美豪丽致酒店(西安未央路店)                       [大明宫万达/大明宫遗址公园]\n未央路149号(凤城三路与未央路十字东北角)地铁2号线图书...   
维慕智能酒店(西安高铁北客站旗舰店)                        [西安高铁站火车北站/西安市政中心]\n凤城十一路与文景路十字向西50米\n\n\n地图   
西安悦豪酒店                                        [西安市高新技术开发区]\n二环南路西段180号\n\n\n地图\n\n\n街景   
秦唐一号酒店(西安钟楼店)                                       [钟鼓楼/回民街/市中心]\n南大街东木头市176号\n\n\n地图   
如家精选酒店(西安钟楼店)                         [钟鼓楼/回民街/市中心]\n南大街8号(和西贝莜面村同一栋楼)\n\n\n地图\n\n\n街景   
甲字精品酒店(西安钟楼回民街店)                                  [钟鼓楼/回民街/市中心]\n案板街3号\n\n\n地图\n\n\n街景   
陕西世纪金源大饭店                                                [新城区]\n建工路19号\n\n\n地图\n\n\n街景   
西安钟楼回民街亚朵酒店                                              [钟鼓楼/回民街/市中心]\n莲湖路23号\n\n\n地图   
美丽豪酒店(西安曲江大雁塔小寨会展中心店)                     [电视塔/国展中心]\n长安南路86A号长丰国际广场A座\n\n\n地图\n\n\n街景   
璞隐酒店(西安大雁塔店)                                               [大雁塔/曲江旅游区]\n红专南路8号\n\n\n地图   
美豪酒店(西安龙首店)                          [北关/龙首村]\n龙首原十字北200米路西荣豪大厦(地铁2号线龙首原站A出口向北200米)...   
喜客五间唐中式酒店(西安大雁塔博物馆小寨会展中心店)(原小寨大雁塔店)       [大雁塔/曲江旅游区]\n翠华南路与红专南路丁字口西北角\n\n\n地图\n\n\n街景   
西安皇城豪门酒店                                        [钟鼓楼/回民街/市中心]\n东大街334号\n\n\n地图\n\n\n街景   
西安荣民国际饭店                                        [钟鼓楼/回民街/市中心]\n西大街126号\n\n\n地图\n\n\n街景   
丽途精选酒店(西安大雁塔曲江店)                                   [大雁塔/曲江旅游区]\n西影路63号\n\n\n地图\n\n\n街景   
华辰酒店(西安钟楼东大街明城墙店)                                       [钟鼓楼/回民街/市中心]\n和平路105号\n\n\n地图   
西安阳光国际大酒店                                               [钟鼓楼/回民街/市中心]\n解放路177号\n\n\n地图   
西安阳光国际大酒店                                               [钟鼓楼/回民街/市中心]\n解放路177号\n\n\n地图   
柠檬酒店(西安金花店)                                [城东/西京医院/小商品批发市场]\n长乐中路240号\n\n\n地图\n\n\n街景   
斯维登精品公寓(西安钟楼火车站)                           [钟鼓楼/回民街/市中心]\n西二路21号(地铁四号线五路口站F

In [255]:
newdata[['价格','收藏','评分','已购人数','dist']].corr()

价格        收藏        评分      已购人数      dist
价格    1.000000 -0.141047  0.148029  0.289808 -0.111519
收藏   -0.141047  1.000000  0.024862 -0.052266  0.068849
评分    0.148029  0.024862  1.000000 -0.022773  0.008869
已购人数  0.289808 -0.052266 -0.022773  1.000000 -0.273764
dist -0.111519  0.068849  0.008869 -0.273764  1.000000

In [256]:
mean(dist)

543.7711528619449